#!/bin/sh -e

# Created by Yuri Govorushchenko on 3-apr-13.
# Copyright 2013 nix. All rights reserved.

# Script gets .app file and packages it into an .ipa wrapper re-signing with Appstore profile based on new bundle id.
# Script requires that _last_build_vars.sh is already generated (i.e. SaveBuildEnvVars.sh should have beed executed before launching this script).

currentScriptDir=$(cd "$(dirname "$0")"; pwd)

source "${currentScriptDir}/LoadBuildEnvVars.sh"

IPA_PRODUCT="${BUILT_PRODUCTS_DIR}/${EXECUTABLE_NAME}-${TARGET_NAME}-${CONFIGURATION}-Appstore.ipa"
echo "IPA_PRODUCT = ${IPA_PRODUCT}"

# create temp build
INFOPLIST_NAME=$(basename "${APP_INFOPLIST_FILE}")
TEMP_APP_PRODUCT="${BUILT_PRODUCTS_DIR}/TempAppStore.app"
TEMP_APP_INFOPLIST_FILE="${TEMP_APP_PRODUCT}/${INFOPLIST_NAME}"

remove_temp_appstore_app() {
    rm -rf "${TEMP_APP_PRODUCT}"
}

cp -r "${APP_PRODUCT}" "${TEMP_APP_PRODUCT}"

# change 'Configuration' value in the plist
/usr/libexec/PlistBuddy -c "Set Configuration Appstore" "${TEMP_APP_INFOPLIST_FILE}" \
||
{
    echo "'Configuration' key does not exist in the plist '${TEMP_APP_INFOPLIST_FILE}'"
    remove_temp_appstore_app
    exit 1
}

# resign and create IPA
{
    python "${currentScriptDir}/Resign.py" --app-product-path="${TEMP_APP_PRODUCT}" \
    --new-ipa-path="${IPA_PRODUCT}" \
    --profile-type="appstore" \
    --new-bundle-id="${RESIGNED_BUNDLE_ID}" \
    --new-bundle-name="${RESIGNED_BUNDLE_NAME}" \
    --new-entitlements-path="${RESIGNED_ENTITLEMENTS_PATH}" \
    &&
    echo "# generated by '${0}':
    IPA_PRODUCT=\"${IPA_PRODUCT}\"
    IPA_BUNDLE_ID=\"${RESIGNED_BUNDLE_ID}\"
    NAME_FOR_DEPLOYMENT=\"Appstore\"
    " >> _last_build_vars.sh
} \
||
true

# remove temp appstore app build
remove_temp_appstore_app
