#!/bin/sh -e

# Created by Yuri Govorushchenko on 3-apr-13.
# Copyright 2013 nix. All rights reserved.

# Script gets .app file and packages it into an .ipa wrapper re-signing with iPhone Developer profile based on new bundle id.
# Script requires that _last_build_vars.sh is already generated (i.e. SaveBuildEnvVars.sh should have beed executed before launching this script).

currentScriptDir=$(cd "$(dirname "$0")"; pwd)

source "${currentScriptDir}/LoadBuildEnvVars.sh"

IPA_PRODUCT="${BUILT_PRODUCTS_DIR}/${EXECUTABLE_NAME}-${TARGET_NAME}-${CONFIGURATION}-Resigned.ipa"
echo "IPA_PRODUCT = ${IPA_PRODUCT}"

python "${currentScriptDir}/Resign.py" --app-product-path="${APP_PRODUCT}" \
--new-ipa-path="${IPA_PRODUCT}" \
--profile-type="developer" \
--new-bundle-id="${RESIGNED_BUNDLE_ID}" \
--new-bundle-name="${RESIGNED_BUNDLE_NAME}" \
--new-entitlements-path="${RESIGNED_ENTITLEMENTS_PATH}"

echo "# generated by '${0}':
IPA_PRODUCT=\"${IPA_PRODUCT}\"
IPA_BUNDLE_ID=\"${RESIGNED_BUNDLE_ID}\"
NAME_FOR_DEPLOYMENT=\"${CONFIGURATION}\"
" >> _last_build_vars.sh